### ISSUE TITLE
Supplementary tables from Harris et al. 2021

### ISSUE THREAD

**Issue by znicholls** [wri/carbon-budget#21]
Hi there,

Thanks for making all the code to run your model openly available (including Docker containers, really helpful). I have what I think is a much more basic question: do you have the code to make your supplementary tables in this repository (and if not, would you be willing to add it)? In particular it would be great to see how Table S6 compiles other data sources together.

Thanks!

**Comment by dagibbs22** [comment]
Hi Zeb, 

Thanks for your question. First, I was wondering-- are you running the forest carbon flux model yourself? If so, what are you doing with it? I like to know how people are using the model, especially if they are going so far as to run it themselves.

As for how to make Table S6 (emission and removal factors)-- I had to do a lot of post-processing to get that information, some of which involves a huge cloud computing job to convert the model output and various contextual layers into giant zonal statistics tables (https://github.com/wri/gfw_forest_loss_geotrellis/tree/develop/src/main/scala/org/globalforestwatch/summarystats/carbonflux). I don't think you could easily do this, and it's not something that lends itself to being on GitHub because it's not just another script. If you want the original values behind the emission and removal factors, I'm happy to share them. If you're trying to do something else, let me know what that is and we can figure out how to do it. Happy to email about this if you prefer. I'm at david.gibbs@wri.org.

David

**Comment by znicholls** [comment]
Hi David,

Thanks for your response! Sorry I should have made what I'm doing clearer (and I completely understand the interest in what people are up to, it's the same with the models we develop). No I'm not running the model myself. Instead, with some colleagues, we're just looking to do a sensitivity analysis based on varying above ground removal factors provided in Table S6 over a vaguely sensible range. So, what we were hoping to do was get an estimate of the uncertainty on the above ground removal factors in Table S6. They don't need to be perfect, but even order of magnitude values would be incredibly helpful. 

Cheers,

Zeb

**Comment by dagibbs22** [comment]
Hi Zeb,

Unfortunately we don't have uncertainty for the exact values we present in Table S6 (climate domain by primary/old secondary/young secondary/plantations); our uncertainty analysis was configured somewhat differently. For our uncertainty analysis, we used uncertainty in aboveground and belowground removal factors for new and existing forest by climate domain. I've attached the relevant values from the uncertainty analysis. I don't know whether you want to use the existing or new forest RF variances in the spreadsheet; in the model, the vast majority of pixels were "existing" forest rather than "new" forest, so I'd pick the former if you want to base your uncertainty on numerical dominance. Let me know if you have any questions. 

[flux_model_RF_uncertainty_by_domain_v1.2.0__20210913.xlsx](https://github.com/wri/carbon-budget/files/7157234/flux_model_RF_uncertainty_by_domain_v1.2.0__20210913.xlsx)

David

**Comment by znicholls** [comment]
Hi David,

No worries, thanks for providing that: very helpful nonetheless! Can I just confirm one thing: AGC is 'above ground carbon' i.e. the units are C and not CO2e?

Cheers,

Zeb

**Comment by dagibbs22** [comment]
Hi Zeb,

AGC is aboveground carbon and the units are C, not CO2e. 

Do you think you'll use the uncertainty values I sent in your analysis? Just curious.

David

**Comment by znicholls** [comment]
Thanks! Yes we think they're the best thing available so have updated from the previous source we were using.

Cheers,

Zeb

**Comment by znicholls** [comment]
Do you have a zenodo reference or similar for the file above we should use?

**Comment by dagibbs22** [comment]
No, I don't have a reference for that file. I thought I'd made a Zenodo reference for the repo overall, but now I can't find that. I don't use Zenodo much. If there's an easy way for me to make a Zenodo reference for that spreadsheet, let me know how and I can do it. Thanks.

**Comment by znicholls** [comment]
You can just login to zenodo using your github login, then click upload and make a new upload. It asks for super basic metadata then gives you a DOI. I've always found it pretty straightforward so hopefully there's no surprises for you but let me know if there are any issues.

**Comment by znicholls** [comment]
Awesome thanks!

> I hope that in addition to citing the specific Zenodo item, you'll cite the paper as well (since that has the details)

Yep absolutely, thanks again for your great work
